# Generated by Django 4.2 on 2024-07-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
